### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by andrecesarlino** [hurik/MangaDownloader#2]
i try go to \src\main\java\de\andreasgiemza\mangadownloader and java -jar MangaDownloader.jar.
java -jar MangaDownloader.java but none worked

**Comment by hurik** [comment]
You can't install it.
1. Download the newest version: https://github.com/hurik/MangaManagerAndDownloader/releases/download/20150817/MangaManagerAndDownloader-20150817.jar
2. Normally when you have Java installed, you can start it with a double click. When that is not working you can open a console, go in the folder with the file and start it with `java -jar MangaManagerAndDownloader-20150817.jar`. When thats also not working you must install java and make sure thats it is in the path.

Is it working now?

I also updated the readme.
