### ISSUE TITLE
Does not seem to update properly

### ISSUE THREAD

**Issue by wyatt8740** [hurik/MangaDownloader#3]
I've gotten and built the latest version from git master, and when I select KissManga and hit 'update', the progress wheel spins for a long time (around a minute or two) and then disappears. I click 'select' to select KissManga to add a subscription, and it says 'Please update site before continuing!' even though I just tried to do that.

I've also noticed bato.to is failing to update.

```
Try 1 of 5. Link: https://bato.to/comic/_/comics/?per_page=1000&st=8000. Error: Read timed out
Try 1 of 5. Link: http://kissmanga.com/MangaList?page=135. Error: Read timed out
```

In addition all the other sites when I hit 'update all' appear to be successful according to the console but they still say 'no list present' and don't let me select them. If it matters, I run debian linux (currently debian 8).

**Comment by hurik** [comment]
this isn't an error ... it only says that on request wasn't working. but it automatically retries it. only when the 5th try doesn't work it gives an error.

i suspect the saving doesn't work. please check your home directory if there is a hidden directory with the name `.MangaDownloader` in the the also should be an `source` directory.

does any of this directory exists?
