### ISSUE TITLE
KissManga works not correctly.

### ISSUE THREAD

**Issue by rosevinnur** [hurik/MangaDownloader#4]
Download empty file.
![default](https://cloud.githubusercontent.com/assets/14951753/10262265/85949e78-69c9-11e5-9abf-a0903ee5b818.png)

**Comment by hurik** [comment]
should be fixed in this version: https://github.com/hurik/MangaManagerAndDownloader/releases/download/20151003/MangaManagerAndDownloader-20151003.jar

**Comment by rosevinnur** [comment]
thanks
