### ISSUE TITLE
trying to write the parser mangachan.ru.

### ISSUE THREAD

**Issue by rosevinnur** [hurik/MangaDownloader#5]
I am trying to write the parser mangachan.ru.
Troubleshootingget a reference to the image of the string line.

package de.andreasgiemza.mangadownloader.sites.implementations.russian;
import de.andreasgiemza.mangadownloader.data.Chapter;
import de.andreasgiemza.mangadownloader.data.Image;
import de.andreasgiemza.mangadownloader.data.Manga;
import de.andreasgiemza.mangadownloader.helpers.JsoupHelper;
import de.andreasgiemza.mangadownloader.sites.Site;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import java.util.Scanner;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

import java.util.regex.Matcher;  
import java.util.regex.Pattern;  
/**
 *
- @author yuuki
  */
  public class Mangachan implements Site  {
  private final String name = "Mangachan";
  private final String url = "http://mangachan.ru/";
  private final List<String> language = Arrays.asList("Russian");
  private final Boolean watermarks = true;
  
  @Override
  public List<Manga> getMangaList() throws Exception {
      List<Manga> mangas = new LinkedList<>();
  
  ```
  Document doc = JsoupHelper.getHTMLPage(url + "/catalog");
  
  Elements nav = doc.select("div[id=pagination]")
          .first().select("span").first().select("a");
  
  
  
  for (int i = 0; i <= 10000; i=i+20) {
      if (i != 0) {
          doc = JsoupHelper.getHTMLPage(url + "/catalog" + "?offset=" + i);
      }
  
      Elements rows = doc.select("div[id=content]").first()
              .select("div[class=content_row]").select("div[class=manga_row1]");
  
      for (Element row : rows) {
          Element link = row.select("a").get(1);
          mangas.add(new Manga(link.attr("abs:href"), link.text()));
      }
  }
  
  
  return mangas;
  ```
  
  }
  
   @Override
  public List<Chapter> getChapterList(Manga manga) throws Exception {
      List<Chapter> chapters = new LinkedList<>();
  
  ```
  Document doc = JsoupHelper.getHTMLPage(manga.getLink());
  
  Elements rows = doc.select("div[class=manga]");
  
  for (Element row : rows) {
      Element link = row.select("a").first();
      chapters.add(new Chapter(manga, link.attr("abs:href"), link.text()));
  }
  
  return chapters;
  ```
  
  }
  
  @Override
    public List<Image> getChapterImageLinks(Chapter chapter) throws Exception {
        List<Image> images = new LinkedList<>();
  
  ```
    String referrer = url + chapter.getLink()+"#page=1";
    Document doc = JsoupHelper.getHTMLPage(referrer);
  /*get html from string line
  "fullimg":["http://im.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_000.webp","http://im2.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_001.webp","http://im.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_002.webp","http://im2.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_003.webp","http://im.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_004.webp","http://im2.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_005.webp","http://im.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_006.webp","http://im2.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_007.webp","http://im.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_008.webp","http://im2.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_009.webp","http://im.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_010.webp","http://im2.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_011.webp","http://im.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_012.webp","http://im2.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_013.webp","http://im.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_014.webp","http://im2.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_015.webp","http://im.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_016.webp","http://im2.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_017.webp","http://im.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_018.webp","http://im2.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_019.webp","http://im.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_020.webp","http://im2.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_021.webp","http://im.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_022.webp","http://im2.mangachan.ru/manganew_webp/t/1318976596_the-neighbours-doll_v0_ch0/the-neighbours-doll_v0_ch0_023.webp",]
  ```
  
  */
                  }
              }
          }
  
  ```
      break;
  }
  ```
  
  }
        return images;
    }
  
    @Override
    public String getName() {
        return name;
    }
  
    @Override
    public String getUrl() {
        return url;
    }
  
    @Override
    public List<String> getLanguage() {
        return language;
    }
  
    @Override
    public Boolean hasWatermarks() {
        return watermarks;
    }
  }

**Comment by hurik** [comment]
hi,

I fixed the getChapterImageLinks function and added the site.Thanks.

But I didn't tested it very much ...please post when you find an error.

bye,
Andreas

**Comment by rosevinnur** [comment]
great. thanks/
So please add readmanga.me
package de.andreasgiemza.mangadownloader.sites.implementations.russian;
import de.andreasgiemza.mangadownloader.data.Chapter;
import de.andreasgiemza.mangadownloader.data.Image;
import de.andreasgiemza.mangadownloader.data.Manga;
import de.andreasgiemza.mangadownloader.helpers.JsoupHelper;
import de.andreasgiemza.mangadownloader.sites.Site;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import java.util.Scanner;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
/**
 *
- @author yuuki
  */
  public class Readmanga implements Site  {
  private final String name = "Readmanga";
  private final String url = "http://readmanga.me";
  private final List<String> language = Arrays.asList("Russian");
  private final Boolean watermarks = true;
  
  @Override
  public List<Manga> getMangaList() throws Exception {
      List<Manga> mangas = new LinkedList<>();
  
  ```
  Document doc = JsoupHelper.getHTMLPage(url + "/list");
  
  Elements nav = doc.select("span[class=pagination]")
          .first().select("a");
  
  
  
  for (int i = 0; i <= 10000; i=i+70) {
      if (i != 0) {
          doc = JsoupHelper.getHTMLPage(url +"/list?offset=" + i);
      }
  
      Elements rows = doc.select("div[class=leftContent]").first().select("div[class=desc]").select("h3");
  
  
      for (Element row : rows) {
          Element link = row.select("a").first();
          mangas.add(new Manga(link.attr("abs:href"), link.text()));
      }
  }
  
  
  return mangas;
  ```
  
  }
  
   @Override
  public List<Chapter> getChapterList(Manga manga) throws Exception {
      List<Chapter> chapters = new LinkedList<>();
  
  ```
  Document doc = JsoupHelper.getHTMLPage(manga.getLink());
  
  Elements rows = doc.select("td[class=\" \"]");
  Elements rows2 = doc.select("td[class=extra-chapter]");
  for (Element row : rows) {
      Element link = row.select("a").first();
      chapters.add(new Chapter(manga, link.attr("abs:href"), link.text()));
  }
   for (Element row : rows2) {
      Element link = row.select("a").first();
      chapters.add(new Chapter(manga, link.attr("abs:href"), link.text()));
  }
  
  return chapters;
  ```
  
  }
  
  @Override
  public List<Image> getChapterImageLinks(Chapter chapter) throws Exception {
      List<Image> images = new LinkedList<>();
  
  ```
  String referrer = url + chapter.getLink() ;
  Document doc = JsoupHelper.getHTMLPage(referrer);
  ```
  
   //var pictures = [{url:"http://hk.mintmanga.com/auto/12/56/51/01.jpg_res.jpg",w:850,h:1230},{url:"http://hk.mintmanga.com/auto/12/56/51/02.jpg_res.jpg",w:850,h:1230},{url:"http://hl.mintmanga.com/auto/12/56/51/03.jpg_res.jpg",w:850,h:1230},{url:"http://hj.mintmanga.com/auto/12/56/51/04.jpg_res.jpg",w:850,h:1230},{url:"http://hg.mintmanga.com/auto/12/56/51/05.jpg_res.jpg",w:850,h:1230},{url:"http://hh.mintmanga.com/auto/12/56/51/06.jpg_res.jpg",w:850,h:1230},{url:"http://hc.mintmanga.com/auto/12/56/51/07.jpg_res.jpg",w:850,h:1230},{url:"http://hb.mintmanga.com/auto/12/56/51/08.jpg_res.jpg",w:850,h:1230},{url:"http://hf.mintmanga.com/auto/12/56/51/09.jpg_res.jpg",w:850,h:1230},{url:"http://hj.mintmanga.com/auto/12/56/51/10.jpg_res.jpg",w:850,h:1230},{url:"http://hg.mintmanga.com/auto/12/56/51/11.jpg_res.jpg",w:850,h:1230},{url:"http://hg.mintmanga.com/auto/12/56/51/12.jpg_res.jpg",w:850,h:1230},{url:"http://hi.mintmanga.com/auto/12/56/51/13.jpg_res.jpg",w:850,h:1230},{url:"http://hb.mintmanga.com/auto/12/56/51/14.jpg_res.jpg",w:850,h:1230},{url:"http://hb.mintmanga.com/auto/12/56/51/15.jpg_res.jpg",w:850,h:1230},{url:"http://hf.mintmanga.com/auto/12/56/51/16.jpg_res.jpg",w:850,h:1230},{url:"http://he.mintmanga.com/auto/12/56/51/17.jpg_res.jpg",w:850,h:1230},{url:"http://hd.mintmanga.com/auto/12/56/51/18.jpg_res.jpg",w:850,h:1230},{url:"http://hd.mintmanga.com/auto/12/56/51/19.jpg_res.jpg",w:850,h:1230},{url:"http://hf.mintmanga.com/auto/12/56/51/20-21.jpg_res.jpg",w:1700,h:1230},{url:"http://hc.mintmanga.com/auto/12/56/51/22-23.jpg_res.jpg",w:1700,h:1230},{url:"http://he.mintmanga.com/auto/12/56/51/24.jpg_res.jpg",w:850,h:1230},{url:"http://hi.mintmanga.com/auto/12/56/51/Credits.jpg_res.jpg",w:1050,h:840}];
                      }
                  }
              }
  
  ```
          break;
      }
  }
  
  return images;
  ```
  
  }
  
  @Override
  public String getName() {
      return name;
  }
  
  @Override
  public String getUrl() {
      return url;
  }
  
  @Override
  public List<String> getLanguage() {
      return language;
  }
  
  @Override
  public Boolean hasWatermarks() {
      return watermarks;
  }
  }

**Comment by hurik** [comment]
Added ReadManga
